name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - amd64
          - arm64

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: us-east1-docker.pkg.dev/crl-ci-images/cockroach/tpc-e
        flavor: prefix=${{ matrix.platform }}-
        labels: |
          org.opencontainers.image.title=TPC-E
          org.opencontainers.image.vendor=Cockroach Labs Inc.
    - name: Build
      uses: docker/build-push-action@v5
      with:
        platforms: "linux/${{ matrix.platform }}"
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=tar,dest=/tmp/${{ matrix.platform }}.tar
    - name: Upload tarball
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}.tar
        path: /tmp/${{ matrix.platform }}.tar
        if-no-files-found: error
        retention-days: 1
