name: Docker test
permissions:
  contents: read
on:
  workflow_call:
  push:
    branches:
    - main
env:
  GAR_REPO: us-east1-docker.pkg.dev/crl-ci-images/cockroach/tpc-e
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.GAR_REPO }}
        labels: |
          org.opencontainers.image.title=TPC-E
          org.opencontainers.image.vendor=Cockroach Labs Inc.
    - name: Build linux-amd64
      uses: docker/build-push-action@v5
      with:
        platforms: "linux/amd64"
        context: .
        tags: "${{ env.GAR_REPO }}:amd64-${{ github.sha }}"
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true
    - name: Build linux-arm64
      uses: docker/build-push-action@v5
      with:
        platforms: "linux/arm64"
        context: .
        tags: "${{ env.GAR_REPO }}:arm64-${{ github.sha }}"
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true
    - name: list docker images
      run: |
        docker image ls -a
        echo docker push $GAR_REPO:amd64-${{ github.sha }}
        echo docker push $GAR_REPO:arm64-${{ github.sha }}
        echo ${{ steps.meta.outputs.tags }}
        echo docker push $GAR_REPO:amd64-${{ github.sha }}
        echo docker push $GAR_REPO:arm64-${{ github.sha }}
        echo docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          $GAR_REPO:amd64-${{ github.sha }} $GAR_REPO:arm64-${{ github.sha }}
