name: Docker test
permissions:
  contents: read
on:
  workflow_call:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: us-east1-docker.pkg.dev/crl-ci-images/cockroach/tpc-e
        labels: |
          org.opencontainers.image.title=TPC-E
          org.opencontainers.image.vendor=Cockroach Labs Inc.
    - name: Build
      uses: docker/build-push-action@v5
      with:
        platforms: "linux/${{ matrix.platform }}"
        context: .
        tags: "$(for t in ${{ steps.meta.outputs.tags }}; do echo -n ${{ matrix.platform }}-$t; done)"
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=tar,dest=/tmp/${{ matrix.platform }}.tar
    - name: Upload tarball
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}.tar
        path: /tmp/${{ matrix.platform }}.tar
        if-no-files-found: error
        retention-days: 1
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download images
      uses: actions/download-artifact@v4
      with:
        path: /tmp/images
        pattern: "*.tar"
        merge-multiple: true
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Load images
      run: |
        docker load --input /tmp/images/arm64.tar
        docker load --input /tmp/images/amd64.tar
    - name: Create manifest
      run: |
        docker manifest create 
        docker load --input /tmp/images/amd64.tar
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: us-east1-docker.pkg.dev/crl-ci-images/cockroach/tpc-e
    - name: list images
      run: |
        docker images
