name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - amd64
          - arm64

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: us-east1-docker.pkg.dev/crl-ci-images/cockroach/tpc-e
        labels: |
          org.opencontainers.image.title=TPC-E
          org.opencontainers.image.vendor=Cockroach Labs Inc.
    - name: Build
      uses: docker/build-push-action@v5
      with:
        platforms: "linux/${{ matrix.platform }}"
        context: .
        tags: "$(for t in ${{ steps.meta.outputs.tags }}; do echo -n ${{ matrix.platform }}-$t; done)"
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=tar,dest=/tmp/${{ matrix.platform }}.tar
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
