name: windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - run: bash -c 'if [[ $(uname -s) == "MINGW64_NT"* ]]; then echo cool; fi'
    - run: bash -c "uname -om"
    - run: bash -c "uname -a"
    - run: bash -c "uname -o"
  mac-amd64:
    runs-on: macos-latest
    steps:
    - run: bash -c "uname -om"
    - run: bash -c "uname -m"
    - run: bash -c "uname -a"
    - run: bash -c "uname -v"
    - run: bash -c "uname -sm"

    
